# $Revision: 9582 $ $Date: 2008-12-29 10:05:29 -0800 (Mon, 29 Dec 2008) $
# Copyright (c) Bullseye Testing Technology

# Linux kernel 2.6.x makefile for building sample module
# See http://www.bullseye.com/help/env_linuxKernel.html

obj-m := hello.o
