// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_dynamic.proto

#ifndef PROTOBUF_test_5fdynamic_2eproto__INCLUDED
#define PROTOBUF_test_5fdynamic_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_test_5fdynamic_2eproto();
void protobuf_AssignDesc_test_5fdynamic_2eproto();
void protobuf_ShutdownFile_test_5fdynamic_2eproto();

class TestDynamicTest;

// ===================================================================

class TestDynamicTest : public ::google::protobuf::Message {
public:
    TestDynamicTest();
    virtual ~TestDynamicTest();

    TestDynamicTest(const TestDynamicTest& from);

    inline TestDynamicTest& operator=(const TestDynamicTest& from) {
        CopyFrom(from);
        return *this;
    }

    inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
        return _unknown_fields_;
    }

    inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
        return &_unknown_fields_;
    }

    static const ::google::protobuf::Descriptor* descriptor();
    static const TestDynamicTest& default_instance();

    void Swap(TestDynamicTest* other);

    // implements Message ----------------------------------------------

    TestDynamicTest* New() const;
    void CopyFrom(const ::google::protobuf::Message& from);
    void MergeFrom(const ::google::protobuf::Message& from);
    void CopyFrom(const TestDynamicTest& from);
    void MergeFrom(const TestDynamicTest& from);
    void Clear();
    bool IsInitialized() const;

    int ByteSize() const;
    bool MergePartialFromCodedStream(
        ::google::protobuf::io::CodedInputStream* input);
    void SerializeWithCachedSizes(
        ::google::protobuf::io::CodedOutputStream* output) const;
    ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
    int GetCachedSize() const {
        return _cached_size_;
    }
private:
    void SharedCtor();
    void SharedDtor();
    void SetCachedSize(int size) const;
public:

    ::google::protobuf::Metadata GetMetadata() const;

    // nested types ----------------------------------------------------

    // accessors -------------------------------------------------------

    // optional string name = 1;
    inline bool has_name() const;
    inline void clear_name();
    static const int kNameFieldNumber = 1;
    inline const ::std::string& name() const;
    inline void set_name(const ::std::string& value);
    inline void set_name(const char* value);
    inline void set_name(const char* value, size_t size);
    inline ::std::string* mutable_name();
    inline ::std::string* release_name();

    // @@protoc_insertion_point(class_scope:TestDynamicTest)
private:
    inline void set_has_name();
    inline void clear_has_name();

    ::google::protobuf::UnknownFieldSet _unknown_fields_;

    ::std::string* name_;

    mutable int _cached_size_;
    ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

    friend void  protobuf_AddDesc_test_5fdynamic_2eproto();
    friend void protobuf_AssignDesc_test_5fdynamic_2eproto();
    friend void protobuf_ShutdownFile_test_5fdynamic_2eproto();

    void InitAsDefaultInstance();
    static TestDynamicTest* default_instance_;
};
// ===================================================================


// ===================================================================

// TestDynamicTest

// optional string name = 1;
inline bool TestDynamicTest::has_name() const {
    return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TestDynamicTest::set_has_name() {
    _has_bits_[0] |= 0x00000001u;
}
inline void TestDynamicTest::clear_has_name() {
    _has_bits_[0] &= ~0x00000001u;
}
inline void TestDynamicTest::clear_name() {
    if (name_ != &::google::protobuf::internal::kEmptyString) {
        name_->clear();
    }
    clear_has_name();
}
inline const ::std::string& TestDynamicTest::name() const {
    return *name_;
}
inline void TestDynamicTest::set_name(const ::std::string& value) {
    set_has_name();
    if (name_ == &::google::protobuf::internal::kEmptyString) {
        name_ = new ::std::string;
    }
    name_->assign(value);
}
inline void TestDynamicTest::set_name(const char* value) {
    set_has_name();
    if (name_ == &::google::protobuf::internal::kEmptyString) {
        name_ = new ::std::string;
    }
    name_->assign(value);
}
inline void TestDynamicTest::set_name(const char* value, size_t size) {
    set_has_name();
    if (name_ == &::google::protobuf::internal::kEmptyString) {
        name_ = new ::std::string;
    }
    name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TestDynamicTest::mutable_name() {
    set_has_name();
    if (name_ == &::google::protobuf::internal::kEmptyString) {
        name_ = new ::std::string;
    }
    return name_;
}
inline ::std::string* TestDynamicTest::release_name() {
    clear_has_name();
    if (name_ == &::google::protobuf::internal::kEmptyString) {
        return NULL;
    } else {
        ::std::string* temp = name_;
        name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
        return temp;
    }
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_test_5fdynamic_2eproto__INCLUDED
