// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "wordcount.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace dstream {

namespace {

const ::google::protobuf::Descriptor* WordCountRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
WordCountRequest_reflection_ = NULL;
const ::google::protobuf::Descriptor* WordCountResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
WordCountResponse_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_wordcount_2eproto() {
    protobuf_AddDesc_wordcount_2eproto();
    const ::google::protobuf::FileDescriptor* file =
        ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
            "wordcount.proto");
    GOOGLE_CHECK(file != NULL);
    WordCountRequest_descriptor_ = file->message_type(0);
    static const int WordCountRequest_offsets_[2] = {
        GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WordCountRequest, word_),
        GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WordCountRequest, counts_),
    };
    WordCountRequest_reflection_ =
        new ::google::protobuf::internal::GeneratedMessageReflection(
        WordCountRequest_descriptor_,
        WordCountRequest::default_instance_,
        WordCountRequest_offsets_,
        GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WordCountRequest, _has_bits_[0]),
        GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WordCountRequest, _unknown_fields_),
        -1,
        ::google::protobuf::DescriptorPool::generated_pool(),
        ::google::protobuf::MessageFactory::generated_factory(),
        sizeof(WordCountRequest));
    WordCountResponse_descriptor_ = file->message_type(1);
    static const int WordCountResponse_offsets_[2] = {
        GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WordCountResponse, word_),
        GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WordCountResponse, counts_),
    };
    WordCountResponse_reflection_ =
        new ::google::protobuf::internal::GeneratedMessageReflection(
        WordCountResponse_descriptor_,
        WordCountResponse::default_instance_,
        WordCountResponse_offsets_,
        GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WordCountResponse, _has_bits_[0]),
        GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WordCountResponse, _unknown_fields_),
        -1,
        ::google::protobuf::DescriptorPool::generated_pool(),
        ::google::protobuf::MessageFactory::generated_factory(),
        sizeof(WordCountResponse));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
    ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                                       &protobuf_AssignDesc_wordcount_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
    protobuf_AssignDescriptorsOnce();
    ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
        WordCountRequest_descriptor_, &WordCountRequest::default_instance());
    ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
        WordCountResponse_descriptor_, &WordCountResponse::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_wordcount_2eproto() {
    delete WordCountRequest::default_instance_;
    delete WordCountRequest_reflection_;
    delete WordCountResponse::default_instance_;
    delete WordCountResponse_reflection_;
}

void protobuf_AddDesc_wordcount_2eproto() {
    static bool already_here = false;
    if (already_here) {
        return;
    }
    already_here = true;
    GOOGLE_PROTOBUF_VERIFY_VERSION;

    ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
        "\n\017wordcount.proto\022\007dstream\"0\n\020WordCountR"
        "equest\022\014\n\004word\030\001 \001(\t\022\016\n\006counts\030\002 \001(\005\"1\n\021"
        "WordCountResponse\022\014\n\004word\030\001 \001(\t\022\016\n\006count"
        "s\030\002 \001(\005", 127);
    ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
        "wordcount.proto", &protobuf_RegisterTypes);
    WordCountRequest::default_instance_ = new WordCountRequest();
    WordCountResponse::default_instance_ = new WordCountResponse();
    WordCountRequest::default_instance_->InitAsDefaultInstance();
    WordCountResponse::default_instance_->InitAsDefaultInstance();
    ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_wordcount_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_wordcount_2eproto {
    StaticDescriptorInitializer_wordcount_2eproto() {
        protobuf_AddDesc_wordcount_2eproto();
    }
} static_descriptor_initializer_wordcount_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int WordCountRequest::kWordFieldNumber;
const int WordCountRequest::kCountsFieldNumber;
#endif  // !_MSC_VER

WordCountRequest::WordCountRequest()
    : ::google::protobuf::Message() {
    SharedCtor();
}

void WordCountRequest::InitAsDefaultInstance() {
}

WordCountRequest::WordCountRequest(const WordCountRequest& from)
    : ::google::protobuf::Message() {
    SharedCtor();
    MergeFrom(from);
}

void WordCountRequest::SharedCtor() {
    _cached_size_ = 0;
    word_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    counts_ = 0;
    ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

WordCountRequest::~WordCountRequest() {
    SharedDtor();
}

void WordCountRequest::SharedDtor() {
    if (word_ != &::google::protobuf::internal::kEmptyString) {
        delete word_;
    }
    if (this != default_instance_) {
    }
}

void WordCountRequest::SetCachedSize(int size) const {
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _cached_size_ = size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* WordCountRequest::descriptor() {
    protobuf_AssignDescriptorsOnce();
    return WordCountRequest_descriptor_;
}

const WordCountRequest& WordCountRequest::default_instance() {
    if (default_instance_ == NULL) {
        protobuf_AddDesc_wordcount_2eproto();
    }
    return *default_instance_;
}

WordCountRequest* WordCountRequest::default_instance_ = NULL;

WordCountRequest* WordCountRequest::New() const {
    return new WordCountRequest;
}

void WordCountRequest::Clear() {
    if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
        if (has_word()) {
            if (word_ != &::google::protobuf::internal::kEmptyString) {
                word_->clear();
            }
        }
        counts_ = 0;
    }
    ::memset(_has_bits_, 0, sizeof(_has_bits_));
    mutable_unknown_fields()->Clear();
}

bool WordCountRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
    ::google::protobuf::uint32 tag;
    while ((tag = input->ReadTag()) != 0) {
        switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
            // optional string word = 1;
        case 1: {
            if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
                ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
                DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                        input, this->mutable_word()));
                ::google::protobuf::internal::WireFormat::VerifyUTF8String(
                    this->word().data(), this->word().length(),
                    ::google::protobuf::internal::WireFormat::PARSE);
            } else {
                goto handle_uninterpreted;
            }
            if (input->ExpectTag(16)) {
                goto parse_counts;
            }
            break;
        }

        // optional int32 counts = 2;
        case 2: {
            if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
                ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
parse_counts:
                DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive <
                     ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32 > (
                         input, &counts_)));
                set_has_counts();
            } else {
                goto handle_uninterpreted;
            }
            if (input->ExpectAtEnd()) {
                return true;
            }
            break;
        }

        default: {
handle_uninterpreted:
            if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
                ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
                return true;
            }
            DO_(::google::protobuf::internal::WireFormat::SkipField(
                    input, tag, mutable_unknown_fields()));
            break;
        }
        }
    }
    return true;
#undef DO_
}

void WordCountRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
    // optional string word = 1;
    if (has_word()) {
        ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->word().data(), this->word().length(),
            ::google::protobuf::internal::WireFormat::SERIALIZE);
        ::google::protobuf::internal::WireFormatLite::WriteString(
            1, this->word(), output);
    }

    // optional int32 counts = 2;
    if (has_counts()) {
        ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->counts(), output);
    }

    if (!unknown_fields().empty()) {
        ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
            unknown_fields(), output);
    }
}

::google::protobuf::uint8* WordCountRequest::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
    // optional string word = 1;
    if (has_word()) {
        ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->word().data(), this->word().length(),
            ::google::protobuf::internal::WireFormat::SERIALIZE);
        target =
            ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
                1, this->word(), target);
    }

    // optional int32 counts = 2;
    if (has_counts()) {
        target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->counts(), target);
    }

    if (!unknown_fields().empty()) {
        target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
                     unknown_fields(), target);
    }
    return target;
}

int WordCountRequest::ByteSize() const {
    int total_size = 0;

    if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
        // optional string word = 1;
        if (has_word()) {
            total_size += 1 +
                          ::google::protobuf::internal::WireFormatLite::StringSize(
                              this->word());
        }

        // optional int32 counts = 2;
        if (has_counts()) {
            total_size += 1 +
                          ::google::protobuf::internal::WireFormatLite::Int32Size(
                              this->counts());
        }

    }
    if (!unknown_fields().empty()) {
        total_size +=
            ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
                unknown_fields());
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _cached_size_ = total_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    return total_size;
}

void WordCountRequest::MergeFrom(const ::google::protobuf::Message& from) {
    GOOGLE_CHECK_NE(&from, this);
    const WordCountRequest* source =
        ::google::protobuf::internal::dynamic_cast_if_available<const WordCountRequest*>(
            &from);
    if (source == NULL) {
        ::google::protobuf::internal::ReflectionOps::Merge(from, this);
    } else {
        MergeFrom(*source);
    }
}

void WordCountRequest::MergeFrom(const WordCountRequest& from) {
    GOOGLE_CHECK_NE(&from, this);
    if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
        if (from.has_word()) {
            set_word(from.word());
        }
        if (from.has_counts()) {
            set_counts(from.counts());
        }
    }
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void WordCountRequest::CopyFrom(const ::google::protobuf::Message& from) {
    if (&from == this) {
        return;
    }
    Clear();
    MergeFrom(from);
}

void WordCountRequest::CopyFrom(const WordCountRequest& from) {
    if (&from == this) {
        return;
    }
    Clear();
    MergeFrom(from);
}

bool WordCountRequest::IsInitialized() const {

    return true;
}

void WordCountRequest::Swap(WordCountRequest* other) {
    if (other != this) {
        std::swap(word_, other->word_);
        std::swap(counts_, other->counts_);
        std::swap(_has_bits_[0], other->_has_bits_[0]);
        _unknown_fields_.Swap(&other->_unknown_fields_);
        std::swap(_cached_size_, other->_cached_size_);
    }
}

::google::protobuf::Metadata WordCountRequest::GetMetadata() const {
    protobuf_AssignDescriptorsOnce();
    ::google::protobuf::Metadata metadata;
    metadata.descriptor = WordCountRequest_descriptor_;
    metadata.reflection = WordCountRequest_reflection_;
    return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int WordCountResponse::kWordFieldNumber;
const int WordCountResponse::kCountsFieldNumber;
#endif  // !_MSC_VER

WordCountResponse::WordCountResponse()
    : ::google::protobuf::Message() {
    SharedCtor();
}

void WordCountResponse::InitAsDefaultInstance() {
}

WordCountResponse::WordCountResponse(const WordCountResponse& from)
    : ::google::protobuf::Message() {
    SharedCtor();
    MergeFrom(from);
}

void WordCountResponse::SharedCtor() {
    _cached_size_ = 0;
    word_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    counts_ = 0;
    ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

WordCountResponse::~WordCountResponse() {
    SharedDtor();
}

void WordCountResponse::SharedDtor() {
    if (word_ != &::google::protobuf::internal::kEmptyString) {
        delete word_;
    }
    if (this != default_instance_) {
    }
}

void WordCountResponse::SetCachedSize(int size) const {
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _cached_size_ = size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* WordCountResponse::descriptor() {
    protobuf_AssignDescriptorsOnce();
    return WordCountResponse_descriptor_;
}

const WordCountResponse& WordCountResponse::default_instance() {
    if (default_instance_ == NULL) {
        protobuf_AddDesc_wordcount_2eproto();
    }
    return *default_instance_;
}

WordCountResponse* WordCountResponse::default_instance_ = NULL;

WordCountResponse* WordCountResponse::New() const {
    return new WordCountResponse;
}

void WordCountResponse::Clear() {
    if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
        if (has_word()) {
            if (word_ != &::google::protobuf::internal::kEmptyString) {
                word_->clear();
            }
        }
        counts_ = 0;
    }
    ::memset(_has_bits_, 0, sizeof(_has_bits_));
    mutable_unknown_fields()->Clear();
}

bool WordCountResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
    ::google::protobuf::uint32 tag;
    while ((tag = input->ReadTag()) != 0) {
        switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
            // optional string word = 1;
        case 1: {
            if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
                ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
                DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                        input, this->mutable_word()));
                ::google::protobuf::internal::WireFormat::VerifyUTF8String(
                    this->word().data(), this->word().length(),
                    ::google::protobuf::internal::WireFormat::PARSE);
            } else {
                goto handle_uninterpreted;
            }
            if (input->ExpectTag(16)) {
                goto parse_counts;
            }
            break;
        }

        // optional int32 counts = 2;
        case 2: {
            if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
                ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
parse_counts:
                DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive <
                     ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32 > (
                         input, &counts_)));
                set_has_counts();
            } else {
                goto handle_uninterpreted;
            }
            if (input->ExpectAtEnd()) {
                return true;
            }
            break;
        }

        default: {
handle_uninterpreted:
            if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
                ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
                return true;
            }
            DO_(::google::protobuf::internal::WireFormat::SkipField(
                    input, tag, mutable_unknown_fields()));
            break;
        }
        }
    }
    return true;
#undef DO_
}

void WordCountResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
    // optional string word = 1;
    if (has_word()) {
        ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->word().data(), this->word().length(),
            ::google::protobuf::internal::WireFormat::SERIALIZE);
        ::google::protobuf::internal::WireFormatLite::WriteString(
            1, this->word(), output);
    }

    // optional int32 counts = 2;
    if (has_counts()) {
        ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->counts(), output);
    }

    if (!unknown_fields().empty()) {
        ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
            unknown_fields(), output);
    }
}

::google::protobuf::uint8* WordCountResponse::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
    // optional string word = 1;
    if (has_word()) {
        ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->word().data(), this->word().length(),
            ::google::protobuf::internal::WireFormat::SERIALIZE);
        target =
            ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
                1, this->word(), target);
    }

    // optional int32 counts = 2;
    if (has_counts()) {
        target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->counts(), target);
    }

    if (!unknown_fields().empty()) {
        target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
                     unknown_fields(), target);
    }
    return target;
}

int WordCountResponse::ByteSize() const {
    int total_size = 0;

    if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
        // optional string word = 1;
        if (has_word()) {
            total_size += 1 +
                          ::google::protobuf::internal::WireFormatLite::StringSize(
                              this->word());
        }

        // optional int32 counts = 2;
        if (has_counts()) {
            total_size += 1 +
                          ::google::protobuf::internal::WireFormatLite::Int32Size(
                              this->counts());
        }

    }
    if (!unknown_fields().empty()) {
        total_size +=
            ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
                unknown_fields());
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _cached_size_ = total_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    return total_size;
}

void WordCountResponse::MergeFrom(const ::google::protobuf::Message& from) {
    GOOGLE_CHECK_NE(&from, this);
    const WordCountResponse* source =
        ::google::protobuf::internal::dynamic_cast_if_available<const WordCountResponse*>(
            &from);
    if (source == NULL) {
        ::google::protobuf::internal::ReflectionOps::Merge(from, this);
    } else {
        MergeFrom(*source);
    }
}

void WordCountResponse::MergeFrom(const WordCountResponse& from) {
    GOOGLE_CHECK_NE(&from, this);
    if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
        if (from.has_word()) {
            set_word(from.word());
        }
        if (from.has_counts()) {
            set_counts(from.counts());
        }
    }
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void WordCountResponse::CopyFrom(const ::google::protobuf::Message& from) {
    if (&from == this) {
        return;
    }
    Clear();
    MergeFrom(from);
}

void WordCountResponse::CopyFrom(const WordCountResponse& from) {
    if (&from == this) {
        return;
    }
    Clear();
    MergeFrom(from);
}

bool WordCountResponse::IsInitialized() const {

    return true;
}

void WordCountResponse::Swap(WordCountResponse* other) {
    if (other != this) {
        std::swap(word_, other->word_);
        std::swap(counts_, other->counts_);
        std::swap(_has_bits_[0], other->_has_bits_[0]);
        _unknown_fields_.Swap(&other->_unknown_fields_);
        std::swap(_cached_size_, other->_cached_size_);
    }
}

::google::protobuf::Metadata WordCountResponse::GetMetadata() const {
    protobuf_AssignDescriptorsOnce();
    ::google::protobuf::Metadata metadata;
    metadata.descriptor = WordCountResponse_descriptor_;
    metadata.reflection = WordCountResponse_reflection_;
    return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace dstream

// @@protoc_insertion_point(global_scope)
