### COMAKE2: PLEASE DO NOT DELETE THE FILE
#<cvspath>,trunk/<branch-name>/-,<localrev>,<tag-name>/-,<cleancmd>,<makecmd>,disbuild/-,DEP-<N>,unstable/-
common/esp_rpc,,???,???,make clean,make
    quality/autotest/reportlib/cpp,,356,cpp_2-0-1-1_PD_BL,make clean,make,,DEP-2,
    com/btest/gtest,,9149,gtest_1-1-2-0_PD_BL,,sh build.sh,,DEP-1,
    quality/autotest/bmock,,11606,bmock_1-1-4-0_PD_BL,make clean,make,,DEP-1,
    third-64/boost,,334,boost_1-46-1-101_PD_BL,,,,DEP-1,
    inf/common/share,,254,share_1-0-7-1_PD_BL,make clean,make,,DEP-1,
    inf/common/kylin,,260,kylin_1-0-5-0_PD_BL,make clean,make,,DEP-1,
    inf/common/esp,,153,esp_1-0-5-4_PD_BL,make clean,make,,DEP-1,
    third-64/protobuf,,369,protobuf_2-4-1-300_PD_BL,,,,DEP-1,
