# $Revision: 8779 $ $Date: 2008-05-08 15:32:45 -0700 (Thu, 08 May 2008) $
# Copyright (c) Bullseye Testing Technology

# Linux kernel 2.4 makefile for building sample module
# See http://www.bullseye.com/help/build_linuxKernel.html

obj-m := hello.o

include $(TOPDIR)/Rules.make
