# $Revision: 9582 $ $Date: 2008-12-29 10:05:29 -0800 (Mon, 29 Dec 2008) $
# Copyright (c) Bullseye Testing Technology
# This source file contains confidential proprietary information.

# Linux kernel 2.6.x makefile for building BullseyeCoverage run-time.
# See http://www.bullseye.com/help/env_linuxKernel.html

EXTRA_CFLAGS += -Wno-undef

obj-m := libcov-lkm.o
obj-y := libcov-linuxKernel.o
